(function () {
  const cities = {
    marietta:{name:'Marietta',county:'Cobb County',nearby:'East Cobb, Kennesaw, Smyrna, and nearby Cobb County communities',image:'IMG_6274.jpg',context:'Home moves, garage cleanouts, inherited properties, and furniture replacement are common reasons Marietta customers need a dependable hauling crew'},
    decatur:{name:'Decatur',county:'DeKalb County',nearby:'North Decatur, Avondale Estates, Clarkston, Tucker, and nearby DeKalb communities',image:'IMG_2948.jpg',context:'Compact driveways, apartment access, older homes, and fast move-out schedules make accurate access notes especially useful for Decatur pickups'},
    roswell:{name:'Roswell',county:'North Fulton',nearby:'Alpharetta, Sandy Springs, East Cobb, and nearby North Fulton communities',image:'IMG_2966.jpg',context:'Roswell households often schedule furniture removal, basement cleanouts, garage projects, and outdoor debris pickup during moves or home updates'},
    alpharetta:{name:'Alpharetta',county:'North Fulton',nearby:'Milton, Johns Creek, Roswell, and nearby North Fulton communities',image:'IMG_6411.jpg',context:'Furniture swaps, office clear-outs, move preparation, and larger household cleanouts are common reasons Alpharetta customers contact Big Boys'},
    buford:{name:'Buford',county:'Gwinnett and Hall County area',nearby:'Suwanee, Sugar Hill, Flowery Branch, and nearby northeast Metro Atlanta communities',image:'IMG_2820.jpg',context:'Buford-area pickups range from single appliances and mattresses to mixed garage piles, move-outs, and property cleanouts'},
    lawrenceville:{name:'Lawrenceville',county:'Gwinnett County',nearby:'Suwanee, Duluth, Lilburn, Dacula, and nearby Gwinnett communities',image:'IMG_5771.jpg',context:'Lawrenceville homeowners, renters, and property managers use Big Boys for bulky items, rental turnovers, garage cleanouts, and household clutter'},
    'sandy-springs':{name:'Sandy Springs',county:'North Fulton',nearby:'Dunwoody, Roswell, Brookhaven, Buckhead, and nearby communities',image:'IMG_6412.jpg',context:'Condo rules, elevators, parking, gated access, and busy move schedules make detailed pickup planning valuable in Sandy Springs'},
    kennesaw:{name:'Kennesaw',county:'Cobb County',nearby:'Acworth, Marietta, Woodstock, and nearby Cobb County communities',image:'IMG_6402.jpg',context:'Kennesaw move-outs, furniture replacement, garage projects, and student or rental turnovers can begin with a clear online pricing path'},
    smyrna:{name:'Smyrna',county:'Cobb County',nearby:'Vinings, Marietta, Mableton, and northwest Atlanta communities',image:'IMG_2968.jpg',context:'Smyrna homes, townhomes, apartments, and rental properties often need help with furniture, mixed household junk, and move-related cleanouts'},
    tucker:{name:'Tucker',county:'DeKalb County',nearby:'Northlake, Chamblee, Clarkston, Stone Mountain, and nearby communities',image:'IMG_6464.jpg',context:'Tucker customers can combine furniture, appliances, boxes, garage items, and mixed household clutter in one planned pickup'},
    clarkston:{name:'Clarkston',county:'DeKalb County',nearby:'Decatur, Tucker, Stone Mountain, Avondale Estates, and nearby communities',image:'IMG_2467.jpg',context:'Clarkston pickups can involve apartments, rental turnovers, household moves, and mixed cleanup projects that benefit from clear access notes'},
    chamblee:{name:'Chamblee',county:'DeKalb County',nearby:'Brookhaven, Doraville, Dunwoody, Tucker, and nearby communities',image:'IMG_4667.jpg',context:'Chamblee homeowners, renters, offices, and property teams schedule furniture, appliance, cleanout, and commercial removal projects'},
    brookhaven:{name:'Brookhaven',county:'DeKalb County',nearby:'Buckhead, Chamblee, Dunwoody, North Druid Hills, and nearby communities',image:'IMG_6386.jpg',context:'Brookhaven pickups often involve apartment moves, furniture replacement, estate work, home updates, and household cleanouts'},
    'stone-mountain':{name:'Stone Mountain',county:'DeKalb County',nearby:'Clarkston, Tucker, Lithonia, Decatur, and nearby communities',image:'IMG_4337.jpg',context:'Stone Mountain customers can schedule removal for furniture, appliances, renovation debris, outdoor clutter, and larger mixed cleanouts'}
  };
  const city = cities[document.body.dataset.city];
  if (!city) return;
  document.title = `Junk Removal in ${city.name} GA | Big Boys`;
  document.getElementById('cityName').textContent = city.name;
  const meta = document.createElement('meta'); meta.name = 'keywords'; meta.content = `junk removal ${city.name} GA, furniture removal ${city.name}, appliance pickup ${city.name}, garage cleanout ${city.name}, same-day junk removal ${city.county}`; document.head.append(meta);
  document.getElementById('cityContent').innerHTML = `
    <div class="city-intro"><div><span class="eyebrow">${city.county} service area</span><h2>Local junk removal in ${city.name}</h2><p>${city.context}. Big Boys provides residential and commercial removal with a crew that handles the carrying, loading, and haul-away</p><p>Start by selecting known items or estimating trailer space for a mixed pile. Add stairs, disassembly, parking, gate, elevator, and scheduling details before reviewing the estimate and sending a pickup request</p><div class="cta-row"><a class="btn btn-primary" href="../get-a-price-quote.html">Get My Price</a><a class="btn btn-outline" href="tel:+14706606874">Call (470) 660-6874</a></div></div><figure><img src="../photos/junk-removal/${city.image}" alt="Junk removal work serving ${city.name} Georgia" loading="lazy" decoding="async"><figcaption>Real Big Boys junk removal work near Metro Atlanta</figcaption></figure></div>
    <section class="service-use-cases"><span class="eyebrow muted">Popular local projects</span><h2>Why ${city.name} customers call Big Boys</h2><div class="use-case-grid"><article><span>01</span><p>Furniture, mattress, and appliance replacement</p></article><article><span>02</span><p>Garage, basement, attic, and storage cleanouts</p></article><article><span>03</span><p>Move-outs, downsizing, and estate cleanouts</p></article><article><span>04</span><p>Rental turnover and commercial property cleanup</p></article></div></section>
    <section class="local-guide"><div><span class="eyebrow muted">Prepare for pickup</span><h2>A clearer plan for junk removal in ${city.name}</h2><ol><li><strong>List the biggest pieces first</strong> Couches, mattresses, appliances, and other bulky items are the easiest place to begin</li><li><strong>Choose items or trailer space</strong> A short list works well with item pricing, while mixed cleanouts are often easier to estimate by load</li><li><strong>Share access details</strong> Mention stairs, elevators, gate codes, driveway limitations, parking rules, pets, and carrying distance</li><li><strong>Request the best window</strong> Choose a preferred date and time, then ask about same-day capacity when timing matters</li></ol></div><aside><h3>Have a large or unusual job?</h3><p>Call before booking when the project includes heavy material, several rooms, restricted access, or a strict property deadline</p><a href="tel:+14706606874">Talk with the Team</a></aside></section>
    <section class="city-content-block"><div><span class="eyebrow muted">Pricing guidance</span><h2>What affects a junk removal estimate</h2><p>The amount and type of material are only part of the estimate. Access, weight, disassembly, carrying distance, stairs, parking, route timing, and disposal requirements can also affect the confirmed scope</p><p>Use item pricing for a short list of common pieces. Choose load-size pricing when the job includes boxes, bags, furniture, outdoor items, or mixed contents from several areas. The online estimate is a starting point, and the crew confirms the final scope before work begins</p></div><div><span class="eyebrow muted">Nearby coverage</span><h2>Serving ${city.name} and surrounding communities</h2><p>${city.nearby} are part of the broader Metro Atlanta footprint. Route availability changes with distance, job size, timing, and the active schedule</p><p>If your address sits outside the city page or near the edge of the service area, call before building a full request. The team can confirm whether your ZIP code fits the current Atlanta or Suwanee route</p></div></section>
    <h2>Junk removal services available in ${city.name}</h2><p>Combine several types of non-hazardous material in one pickup when the scope is clear. For a mixed job, load-size pricing may be the simplest starting point</p><div class="area-dir"><a href="../services/furniture-removal.html">Furniture removal</a><a href="../services/appliance-removal.html">Appliance removal</a><a href="../services/mattress-removal.html">Mattress removal</a><a href="../services/cleanouts.html">Home and estate cleanouts</a><a href="../services/yard-waste-removal.html">Yard waste removal</a><a href="../services/construction-debris.html">Construction debris</a><a href="../services/commercial-junk-removal.html">Commercial removal</a></div>
    <section class="city-faq"><span class="eyebrow muted">${city.name} junk removal FAQ</span><h2>Questions before you request pickup</h2><details open><summary>Can I get a price before booking?</summary><p>Yes. Choose item pricing or load-size pricing, add labor and access details, and review the starting estimate before sending a request</p></details><details><summary>Will the crew remove items from inside?</summary><p>Yes, when the location is safely accessible and included in the confirmed scope. Describe stairs, elevators, hallways, gates, parking, and building rules in advance</p></details><details><summary>Can I request same-day service in ${city.name}?</summary><p>Same-day availability depends on the active route, job size, and the time the request is received. Call early when the deadline is important</p></details><details><summary>Can one pickup include furniture and household junk?</summary><p>Yes. You can combine common furniture, appliances, boxes, bags, and other approved non-hazardous material. Load-size pricing may be easier for mixed jobs</p></details><details><summary>What should I separate before the crew arrives?</summary><p>Remove personal documents, valuables, donations, and anything that must stay. Keep hazardous chemicals, fuel, medical waste, and regulated material outside the removal pile</p></details></section>
    <section class="service-local"><h2>Ready to clear the space in ${city.name}</h2><p>Build a starting estimate online or call Big Boys to discuss a larger property cleanout, unusual item, difficult access, or time-sensitive pickup</p><div class="cta-row"><a class="btn btn-primary" href="../get-a-price-quote.html">Start My Estimate</a><a class="btn btn-outline" href="../service-areas/index.html">View All Service Areas</a></div></section>`;

  const shell = document.createElement('script'); shell.src = '../site-shell.js'; shell.dataset.root = '../'; document.body.append(shell);
})();
