(function(){
 const data={
 atlanta:{name:'Atlanta',neighborhoods:'Buckhead, Brookhaven, Chamblee, Decatur, Tucker, and surrounding intown communities',address:'3201 Henderson Mill Road, Atlanta, GA 30341',context:'From apartment moves and neighborhood cleanouts to office furniture and renovation debris, Atlanta jobs often need a crew that can work around stairs, parking, and busy schedules.'},
 suwanee:{name:'Suwanee',neighborhoods:'Buford, Lawrenceville, Duluth, Johns Creek, Sugar Hill, and surrounding Gwinnett communities',address:'2317 Breton Hunt Lane, Suwanee, GA 30024',context:'Suwanee homeowners, renters, and property managers can use Big Boys for bulky furniture, garage cleanouts, appliance pickup, and larger household clear-outs.'}
 }; const key=document.body.dataset.location, c=data[key]; if(!c)return;
 document.title=`Junk Removal in ${c.name}, GA | Big Boys Junk Removal`;
 document.getElementById('locationName').textContent=c.name;
 document.getElementById('locationAddress').textContent=c.address;
 document.getElementById('locationContent').innerHTML=`<h2>Junk removal in ${c.name}, GA</h2><p>${c.context} Big Boys Junk Removal makes it easier to get a starting price online before you request a pickup. Choose individual items when you know what needs to go, or use load-size pricing for a mixed pile.</p><section class="local-guide"><div><span class="eyebrow muted">Before the crew arrives</span><h2>A clearer pickup plan</h2><ol><li><strong>Make a quick list.</strong> Start with the large pieces, then add the smaller items that need to go.</li><li><strong>Choose items or trailer space.</strong> The best option depends on whether your job is a short list or a mixed cleanout.</li><li><strong>Add access notes.</strong> Stairs, parking, elevators, gates, and timing details help us plan the pickup well.</li></ol></div><aside><h3>Have an unusual item?</h3><p>Talk with the team before booking if your job has special access, a large volume, or a heavy item.</p><a href="tel:+14706606874">Call (470) 660-6874</a></aside></section><h2>Services available in ${c.name}</h2><div class="area-dir">${BIG_BOYS.services.map(([n,,h])=>`<a href="../${h}">${n}</a>`).join('')}</div><h2>Nearby areas we serve</h2><p>${c.neighborhoods} are part of the broader Metro Atlanta service footprint. Visit our <a href="../service-areas/index.html">service areas page</a> for more cities.</p><section class="city-faq"><span class="eyebrow muted">${c.name} FAQ</span><h2>Good to know</h2><details open><summary>Can I get a price before booking?</summary><p>Yes. Start with the quote experience to choose items or a load size and review a starting price before you request a pickup.</p></details><details><summary>Do you remove items from inside?</summary><p>The crew handles loading. Tell us about stairs, access, or other relevant details in your pickup request.</p></details><details><summary>Can I ask for same-day service?</summary><p>Same-day availability depends on the current route schedule. Start a quote or call us to check the earliest available pickup.</p></details></section><a class="btn btn-primary" href="../get-a-price-quote.html">Get a Price Quote</a>`;
})();
