(function(){
 const data={
 atlanta:{name:'Atlanta',neighborhoods:'Buckhead, Brookhaven, Chamblee, Decatur, Tucker, and surrounding intown communities',address:'3201 Henderson Mill Road, Atlanta, GA 30341',context:'From apartment moves and neighborhood cleanouts to office furniture and renovation debris, Atlanta jobs often need a crew that can work around stairs, parking, and busy schedules.'},
 suwanee:{name:'Suwanee',neighborhoods:'Buford, Lawrenceville, Duluth, Johns Creek, Sugar Hill, and surrounding Gwinnett communities',address:'2317 Breton Hunt Lane, Suwanee, GA 30024',context:'Suwanee homeowners, renters, and property managers can use Big Boys for bulky furniture, garage cleanouts, appliance pickup, and larger household clear-outs.'}
 }; const key=document.body.dataset.location, c=data[key]; if(!c)return;
 document.title=`Junk Removal in ${c.name}, GA | Big Boys Junk Removal`;
 document.getElementById('locationName').textContent=c.name;
 document.getElementById('locationAddress').textContent=c.address;
 document.getElementById('locationContent').innerHTML=`<h2>Junk removal in ${c.name}, GA</h2><p>${c.context} Big Boys Junk Removal makes it easier to get a starting price online before you request a pickup. Choose individual items when you know what needs to go, or use load-size pricing for a mixed pile.</p><h2>Services available in ${c.name}</h2><div class="area-dir">${BIG_BOYS.services.map(([n,,h])=>`<a href="../${h}">${n}</a>`).join('')}</div><h2>Nearby areas we serve</h2><p>${c.neighborhoods} are part of the broader Metro Atlanta service footprint. Visit our <a href="../service-areas/index.html">service areas page</a> for more cities.</p><h2>Why choose Big Boys?</h2><ul><li>Online starting-price paths by item or by load size</li><li>Crews handle the loading and removal</li><li>Call support for large cleanouts or pickup planning</li></ul><h2>${c.name} junk removal FAQs</h2><h3>Can I get a price before booking?</h3><p>Yes. Start with the quote experience to choose items or a load size and review a starting price before you request a pickup.</p><h3>Do you remove items from inside?</h3><p>The crew handles loading. Tell us about stairs, access, or other relevant details in your pickup request.</p><a class="btn btn-primary" href="../get-a-price-quote.html">Get a Price Quote</a>`;
})();
