(function () {
  const locations = {
    atlanta:{name:'Atlanta',area:'Central and North Metro Atlanta',neighborhoods:'Buckhead, Brookhaven, Chamblee, Decatur, Tucker, Sandy Springs, and surrounding intown communities',address:'3201 Henderson Mill Road, Atlanta, GA 30341',image:'IMG_5771.jpg',context:'Atlanta pickups often involve apartment access, older homes, busy streets, limited parking, office buildings, move deadlines, and properties with several floors'},
    suwanee:{name:'Suwanee',area:'Gwinnett and Northeast Metro Atlanta',neighborhoods:'Buford, Lawrenceville, Duluth, Johns Creek, Sugar Hill, and surrounding Gwinnett communities',address:'2317 Breton Hunt Lane, Suwanee, GA 30024',image:'IMG_4667.jpg',context:'Suwanee projects commonly include bulky furniture, garage cleanouts, appliance replacement, yard debris, downsizing, and larger household clear-outs'}
  };
  const location = locations[document.body.dataset.location];
  if (!location) return;
  document.title = `Junk Removal in ${location.name} GA | Big Boys Junk Removal`;
  document.getElementById('locationName').textContent = location.name;
  document.getElementById('locationAddress').textContent = location.address;
  const meta = document.createElement('meta'); meta.name = 'keywords'; meta.content = `junk removal ${location.name}, same-day junk removal ${location.name}, furniture removal ${location.name}, garage cleanout ${location.name}, appliance pickup Metro Atlanta`; document.head.append(meta);
  document.getElementById('locationContent').innerHTML = `<div class="city-intro"><div><span class="eyebrow">${location.area}</span><h2>Local junk removal in ${location.name}</h2><p>${location.context}. Big Boys provides the crew, carrying, loading, and haul-away for approved residential and commercial material</p><p>Choose individual items for a clear list or estimate trailer space for a mixed job. Include access, timing, stairs, parking, gate, and disassembly details so the team can review a more useful starting estimate</p><div class="cta-row"><a class="btn btn-primary" href="../get-a-price-quote.html">Get My Price</a><a class="btn btn-outline" href="tel:+14706606874">Call (470) 660-6874</a></div></div><figure><img src="../photos/junk-removal/${location.image}" alt="Junk removal work serving ${location.name} Georgia" loading="lazy"><figcaption>Real Big Boys junk removal work in Metro Atlanta</figcaption></figure></div>
    <section class="service-use-cases"><span class="eyebrow muted">Common local projects</span><h2>Junk removal for homes, rentals, and businesses</h2><div class="use-case-grid"><article><span>01</span><p>Furniture, mattress, and appliance removal</p></article><article><span>02</span><p>Garage, basement, and estate cleanouts</p></article><article><span>03</span><p>Move-out and rental turnover cleanup</p></article><article><span>04</span><p>Office, retail, and property removal projects</p></article></div></section>
    <section class="local-guide"><div><span class="eyebrow muted">Before the crew arrives</span><h2>Prepare a clear pickup plan</h2><ol><li><strong>Separate what stays</strong> Remove personal documents, donations, valuables, and anything that should not be loaded</li><li><strong>Choose the pricing method</strong> Select items for a known list or load size for mixed household and project material</li><li><strong>Add access details</strong> Share stairs, parking, elevators, gates, building hours, pets, and carrying distance</li><li><strong>Request a window</strong> Choose a date and time preference, then confirm the route and scope with the team</li></ol></div><aside><h3>Need help with a large cleanout?</h3><p>Call when the job covers several rooms, has difficult access, includes heavy material, or must meet a property deadline</p><a href="tel:+14706606874">Talk with the Team</a></aside></section>
    <section class="city-content-block"><div><span class="eyebrow muted">Upfront estimate options</span><h2>Price a short list or a mixed load</h2><p>Item pricing is useful for couches, mattresses, dressers, tables, appliances, and other known pieces. Load-size pricing is often easier for garages, estates, move-outs, renovation debris, and mixed piles</p><p>Access, stairs, disassembly, weight, route, and disposal requirements can affect the confirmed total. The online estimate helps you organize the request before the final scope review</p></div><div><span class="eyebrow muted">Nearby communities</span><h2>Coverage beyond ${location.name}</h2><p>${location.neighborhoods} are part of the broader service footprint. Availability depends on route capacity, job size, distance, and timing</p><p>Call when your ZIP code is near the edge of the area or when a project has a strict deadline. The team can confirm the current route before you build a full request</p></div></section>
    <h2>Services available in ${location.name}</h2><div class="area-dir">${BIG_BOYS.services.map(([name,,href]) => `<a href="../${href}">${name}</a>`).join('')}</div>
    <section class="city-faq"><span class="eyebrow muted">${location.name} junk removal FAQ</span><h2>Good to know before pickup</h2><details open><summary>Can I get a price before booking?</summary><p>Yes. Choose items or a load size, add labor and access details, and review the starting estimate before sending the request</p></details><details><summary>Does the crew remove items from inside?</summary><p>Yes, when access is safe and included in the confirmed scope. Share stairs, elevators, hallways, gate codes, parking, and building rules before arrival</p></details><details><summary>Can I request same-day service?</summary><p>Same-day service depends on route capacity and job size. Call early when timing is important</p></details><details><summary>Can I combine several types of junk?</summary><p>Yes. Mixed furniture, appliances, boxes, bags, outdoor items, and other approved non-hazardous material can be included in one request</p></details><details><summary>What cannot go in the removal pile?</summary><p>Keep hazardous chemicals, fuel, medical waste, and regulated material separate. Call when you are unsure about a specific item</p></details></section>
    <section class="service-local"><h2>Start junk removal in ${location.name}</h2><p>Build an estimate online or call Big Boys to discuss a larger, unusual, or time-sensitive job</p><div class="cta-row"><a class="btn btn-primary" href="../get-a-price-quote.html">Start My Estimate</a><a class="btn btn-outline" href="../service-areas/index.html">View All Service Areas</a></div></section>`;
})();
