(function(){
  const app=document.getElementById('quoteApp');
  const steps=[...document.querySelectorAll('.quote-steps li')];
  const progress=document.querySelector('.quote-progress i');
  const params=new URLSearchParams(location.search);
  const state={method:'',items:[],load:null,stairs:0,disassembly:0,sameDay:false,zip:params.get('zip')||'',customer:{}};
  const catalog=[
    {name:'Mattress',price:15,icon:'üõèÔ∏è',tag:'Most booked'},
    {name:'Full Box Spring',price:20,icon:'üõè',tag:'Most booked'},
    {name:'Couch / Loveseat',price:30,icon:'üõãÔ∏è',tag:'Most booked'},
    {name:'Dresser',price:20,icon:'üóÑÔ∏è',tag:'Most booked'},
    {name:'Desk',price:20,icon:'ü™ë',tag:'Most booked'},
    {name:'Table',price:25,icon:'-ñ§',tag:'Most booked'},
    {name:'Freezer',price:50,icon:'-ñ•',tag:'Most booked'},
    {name:'Toolbox',price:25,icon:'üß∞',tag:'Most booked'},
    {name:'Recliner',price:90,icon:'üõã',tag:'Most booked'},
    {name:'Bag of Junk',price:20,icon:'-ôªÔ∏è',tag:'Most booked'}
  ];
  const loads=[['1/8',99,'Small'],['2/8',169,'Small'],['3/8',239,'Medium'],['4/8',309,'Medium'],['5/8',399,'Large'],['6/8',499,'Large'],['7/8',599,'Full'],['Full',699,'Full']];
  const setStep=n=>{steps.forEach((el,i)=>el.classList.toggle('active',i<=n));progress.style.width=`${(n+1)*20}%`;scrollTo({top:0,behavior:'smooth'});};
  const button=(label,cls='quote-btn primary',attrs='')=>`<button class="${cls}" type="button" ${attrs}>${label}</button>`;
  const serviceFee=()=>state.method==='item'?49:0;
  const subtotal=()=>state.method==='load'?(state.load?.price||0):state.items.reduce((sum,item)=>sum+item.price*item.qty,0)+serviceFee();
  const total=()=>subtotal()+state.stairs*10+state.disassembly*20+(state.sameDay?20:0);
  const liveAgent=()=>`<aside class="live-agent"><div><span class="agent-icon">-òé</span><p><strong>Speak to a Live Agent</strong><small>Not sure what you need? Talk to a real person.</small><em>Usually responds in 1---2 minutes</em></p></div><a href="contact.html">Request a Callback</a></aside>`;
  function method(){setStep(0);app.innerHTML=`<section class="quote-screen method-screen"><header><h1>How should we price your job?</h1><p>Choose the method that works best for you</p></header><div class="method-grid"><button data-method="item"><span class="method-icon">-ò∑</span><span><strong>Price by Item</strong><small>Select individual items for precise pricing</small></span></button><button data-method="load"><span class="method-icon">-ñ±</span><span><strong>Price by Load Size</strong><small>Choose a truck load size for bulk pricing</small></span></button></div><p class="quote-hint">Not sure? Choose load size for a quick estimate.</p><div class="quote-actions two">${button('-Üê &nbsp; Back','quote-btn secondary','data-back')}${button('Continue','quote-btn primary','disabled data-continue')}</div></section>`;
    let selected='';app.querySelector('[data-back]').onclick=()=>location.href='index.html';app.querySelectorAll('[data-method]').forEach(el=>el.onclick=()=>{selected=el.dataset.method;app.querySelectorAll('[data-method]').forEach(x=>x.classList.toggle('selected',x===el));app.querySelector('[data-continue]').disabled=false;});app.querySelector('[data-continue]').onclick=()=>{state.method=selected;selected==='item'?items():load();};
  }
  function items(){setStep(1);app.innerHTML=`<section class="quote-screen items-screen"><header><h1>What are we picking up?</h1><p>Search or browse ¬∑ Instant upfront pricing</p></header><div class="trust-pills"><span>-ú- No hidden fees</span><span>-óá Save more when you remove more</span></div><div class="availability">-ó∑ Limited same-day slots available</div><h2>Most Popular Items</h2><div class="item-grid">${catalog.map((item,i)=>{const found=state.items.find(x=>x.name===item.name);return `<article class="item-card" data-name="${item.name.toLowerCase()}"><b>${item.tag}</b><span class="item-icon">${item.icon}</span><strong>${item.name}</strong><small>From $${item.price}</small><div class="qty"><button data-minus="${i}" aria-label="Remove one ${item.name}">-àí</button><span data-qty="${i}">${found?.qty||0}</span><button data-plus="${i}" aria-label="Add one ${item.name}">+ Add</button></div></article>`}).join('')}</div><h2>Find Any Item</h2><label class="item-search"><span>-åï</span><input type="search" data-item-search placeholder="Search for anything (e.g. couch, fridge, treadmill, piano--¶)" aria-label="Search items"></label><a class="cant-find" href="contact.html">Can--ôt find your item? We--ôll price it for you.</a><h2>Browse by Category</h2><div class="category-list">${['Furniture','Appliances','Electronics','Outdoor & Yard','Office','Cleanouts & Bulk Jobs','Miscellaneous','Heavy / Specialty Items'].map(x=>`<details><summary>${x}</summary><p>Call or request a callback for ${x.toLowerCase()} not shown above.</p></details>`).join('')}</div><div class="quote-actions">${button('Back','quote-btn secondary','data-back')}${button('Continue','quote-btn primary','data-next')}</div>${liveAgent()}</section>`;
    const quantity=i=>state.items.find(x=>x.name===catalog[i].name)?.qty||0;const search=app.querySelector("[data-item-search]");search.oninput=()=>{const q=search.value.trim().toLowerCase();app.querySelectorAll(".item-card").forEach(card=>card.hidden=!!q&&!card.dataset.name.includes(q));};
    const update=(i,delta)=>{const c=catalog[i];let found=state.items.find(x=>x.name===c.name);if(!found&&delta>0){found={name:c.name,price:c.price,qty:0};state.items.push(found)}if(found)found.qty=Math.max(0,found.qty+delta);state.items=state.items.filter(x=>x.qty>0);app.querySelector(`[data-qty="${i}"]`).textContent=quantity(i);};
    app.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>update(+b.dataset.plus,1));app.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>update(+b.dataset.minus,-1));app.querySelector('[data-back]').onclick=method;app.querySelector('[data-next]').onclick=()=>state.items.length?details():alert('Add at least one item to continue.');
  }
  function load(){setStep(1);app.innerHTML=`<section class="quote-screen load-screen"><header><h1>Select How Much Space You Need</h1><p>Our trailer is <strong>16 ft long √ó 7 ft wide</strong> (standard full load)<br><small>Tap how much of the trailer your items will fill</small></p></header>${state.load?`<div class="load-selection">You selected: <strong>${state.load.name}</strong> of trailer (${state.load.label} Load)<b>$${state.load.price}</b></div>`:'<p class="load-prompt">Select a load size below</p>'}<div class="trailer"><div class="trailer-fill" style="width:${state.load?state.load.index*12.5:0}%"></div>${loads.map(([name,price,label],i)=>`<button data-load="${i}" class="${state.load?.index===i+1?'selected':''}"><span>${name}</span><small>$${price}</small></button>`).join('')}</div><div class="load-labels"><span>Small Load</span><span>Medium Load</span><span>Large Load</span><span>Full Load</span></div><div class="quote-actions">${button('-Üê &nbsp; Back','quote-btn secondary','data-back')}${button('Continue','quote-btn primary','data-next '+(!state.load?'disabled':''))}</div>${liveAgent()}</section>`;app.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>{const i=+b.dataset.load,[name,price,label]=loads[i];state.load={name,price,label,index:i+1};load();});app.querySelector('[data-back]').onclick=method;app.querySelector('[data-next]').onclick=details;
  }
  function details(){setStep(2);app.innerHTML=`<section class="quote-screen details-screen"><header><h1>Job details</h1><p>Any extra considerations?</p></header><div class="detail-option"><span class="detail-icon">-Ü•</span><p><strong>Are there stairs?</strong><small>$10 per stair</small></p><div class="stepper"><button data-stairs-minus>-àí</button><b>${state.stairs}</b><button data-stairs-plus>+</button></div></div><div class="detail-option"><span class="detail-icon">-åï</span><p><strong>Needs disassembly?</strong><small>$20 per item</small></p><div class="stepper"><button data-dis-minus>-àí</button><b>${state.disassembly}</b><button data-dis-plus>+</button></div></div><label class="detail-option toggle-option"><span class="detail-icon">œü</span><p><strong>Same Day Service</strong><small>+$20 ¬∑ Priority pickup today</small></p><input type="checkbox" ${state.sameDay?'checked':''} data-same-day><i></i></label><div class="updated-total"><span>Updated total</span><strong>$${total()}</strong></div><div class="quote-actions">${button('Back','quote-btn secondary','data-back')}${button('See Price','quote-btn primary','data-next')}</div></section>`;
    app.querySelector('[data-stairs-minus]').onclick=()=>{state.stairs=Math.max(0,state.stairs-1);details()};app.querySelector('[data-stairs-plus]').onclick=()=>{state.stairs++;details()};app.querySelector('[data-dis-minus]').onclick=()=>{state.disassembly=Math.max(0,state.disassembly-1);details()};app.querySelector('[data-dis-plus]').onclick=()=>{state.disassembly++;details()};app.querySelector('[data-same-day]').onchange=e=>{state.sameDay=e.target.checked;details()};app.querySelector('[data-back]').onclick=()=>state.method==='item'?items():load();app.querySelector('[data-next]').onclick=price;
  }
  function price(){setStep(3);const lines=state.method==='item'?state.items.map(x=>`<li><span>${x.name} √ó ${x.qty}</span><b>$${x.price*x.qty}</b></li>`):[`<li><span>${state.load.name} trailer load</span><b>$${state.load.price}</b></li>`];if(serviceFee())lines.push(`<li><span>üöö Area Service Fee (transportation & loading)</span><b>$${serviceFee()}</b></li>`);if(state.stairs)lines.push(`<li><span>Stairs √ó ${state.stairs}</span><b>$${state.stairs*10}</b></li>`);if(state.disassembly)lines.push(`<li><span>Disassembly √ó ${state.disassembly}</span><b>$${state.disassembly*20}</b></li>`);if(state.sameDay)lines.push(`<li><span>Same-day priority</span><b>$20</b></li>`);app.innerHTML=`<section class="quote-screen price-screen"><header><h1>Your price</h1></header><div class="price-card"><strong>$${total()}</strong><span>-öô No hidden fees</span></div><ul class="price-lines">${lines.join('')}</ul><ul class="price-trust"><li>-ú- Fully insured</li><li>-ô¢ Background-checked professionals</li><li>-ôß Satisfaction focused</li></ul><div class="quote-actions">${button('Back','quote-btn secondary','data-back')}${button('Book Now','quote-btn primary','data-next')}</div></section>`;app.querySelector('[data-back]').onclick=details;app.querySelector('[data-next]').onclick=book;
  }
  function book(){setStep(4);app.innerHTML=`<section class="quote-screen book-screen"><header><h1>Book your pickup</h1><p>Total: <strong>$${total()}</strong></p>${state.sameDay?'<em>œü Same-day slot requested</em>':''}</header><form id="bookingForm"><input name="name" placeholder="Full name *" required autocomplete="name"><input name="phone" type="tel" placeholder="Phone number *" required autocomplete="tel"><input name="email" type="email" placeholder="Email (optional)" autocomplete="email"><input name="address" placeholder="Pickup address *" required autocomplete="street-address"><input name="date" type="date" required aria-label="Select a date"><fieldset><legend>Time slot</legend><div class="time-slots"><label><input type="radio" name="slot" value="Morning" required><span><b>Morning</b><small>8am --- 12pm</small></span></label><label><input type="radio" name="slot" value="Afternoon"><span><b>Afternoon</b><small>12pm --- 4pm</small></span></label><label><input type="radio" name="slot" value="Evening"><span><b>Evening</b><small>4pm --- 7pm</small></span></label></div></fieldset><textarea name="notes" placeholder="Notes / Special instructions (optional)"></textarea><div class="quote-actions">${button('Back','quote-btn secondary','data-back')}<button class="quote-btn primary" type="submit">Prepare Booking Request</button></div></form></section>`;const dateInput=app.querySelector("input[type=date]");const today=new Date();dateInput.min=[today.getFullYear(),String(today.getMonth()+1).padStart(2,"0"),String(today.getDate()).padStart(2,"0")].join("-");app.querySelector("[data-back]").onclick=price;app.querySelector("form").onsubmit=e=>{e.preventDefault();state.customer=Object.fromEntries(new FormData(e.currentTarget));confirmation();};
  }
  function confirmation(){const job=state.method==='load'?`${state.load.name} trailer load`:state.items.map(x=>`${x.name} √ó ${x.qty}`).join(', ');const subject=encodeURIComponent(`Booking request from ${state.customer.name}`);const body=encodeURIComponent(`Name: ${state.customer.name}\nPhone: ${state.customer.phone}\nEmail: ${state.customer.email||'Not provided'}\nPickup address: ${state.customer.address}\nZIP code: ${state.customer.zip}\nRequested date: ${state.customer.date}\nTime window: ${state.customer.slot}\nEstimated job: ${job}\nEstimated total: $${total()}\nNotes: ${state.customer.notes||'None'}\n\nPlease confirm availability, scope, and final price.`);app.innerHTML=`<section class="quote-screen confirmation"><div class="confirm-icon">-ú-</div><h1>Review and send your request</h1><p>Thanks, ${state.customer.name}. Your estimated total is <strong>$${total()}</strong>. Send the request to Big Boys, then the team can confirm scope and availability.</p><div class="quote-actions"><a class="quote-btn primary" href="mailto:support@bigboysjr.com?subject=${subject}&body=${body}">Send Booking Request</a><a class="quote-btn" href="tel:+14706606874">Call (470) 660-6874</a></div><p class="confirmation-note">Selecting --úSend Booking Request--ù opens a pre-filled email with your pickup details.</p></section>`;}
  const enhanceBookingForm=()=>{const form=app.querySelector('#bookingForm');if(!form||form.querySelector('[name="zip"]'))return;const zip=document.createElement('input');zip.name='zip';zip.inputMode='numeric';zip.maxLength=5;zip.pattern='[0-9]{5}';zip.placeholder='ZIP code *';zip.required=true;zip.autocomplete='postal-code';zip.value=state.zip;zip.setAttribute('aria-label','ZIP code');const address=form.querySelector('[name="address"]');address.insertAdjacentElement('afterend',zip);const submit=form.querySelector('[type="submit"]');if(submit)submit.textContent='Review Booking Request';};
  new MutationObserver(enhanceBookingForm).observe(app,{childList:true,subtree:true});
  method();
})();
