(function () {
  const pages = {
    'furniture-removal': ['Furniture Removal', 'Furniture removal in Atlanta and Suwanee---couches, tables, dressers, and bulky pieces removed from wherever they sit.', 'IMG_6412.jpg', ['Couches, sectionals, recliners, and loveseats', 'Dining tables, chairs, desks, and bookcases', 'Dressers, wardrobes, bed frames, and bedroom sets']],
    'appliance-removal': ['Appliance Removal', 'Appliance removal in Atlanta and Suwanee for old refrigerators, washers, dryers, and other heavy household equipment.', 'IMG_2820.jpg', ['Refrigerators, freezers, and ice makers', 'Washers, dryers, stoves, and dishwashers', 'Small appliances included with a larger pickup']],
    'mattress-removal': ['Mattress Removal & Disposal', 'Mattress removal in Metro Atlanta for mattresses, box springs, bed frames, and bedroom furniture.', 'IMG_6386.jpg', ['Mattresses and box springs', 'Bed frames, headboards, and bedroom sets', 'Pickup from bedrooms, garages, or curbside']],
    'hot-tub-removal': ['Hot Tub Removal', 'Hot tub removal in Metro Atlanta with a clear plan for access, size, and the heavy lifting.', 'IMG_6127.jpg', ['Residential hot tubs and spas', 'Covers, steps, and associated outdoor clutter', 'Access planning before the crew arrives']],
    'yard-waste-removal': ['Yard Waste Removal', 'Yard waste removal in Metro Atlanta for bagged debris, branches, brush, and outdoor clutter.', 'IMG_5080.jpg', ['Bagged leaves and yard debris', 'Branches, brush, and storm cleanup', 'Outdoor furniture and mixed backyard clutter']],
    cleanouts: ['Garage & Basement Cleanouts', 'Garage and basement cleanouts in Metro Atlanta for crowded storage areas, estate cleanouts, and household overflow.', 'IMG_5771.jpg', ['Garage, basement, attic, and storage-room cleanouts', 'Estate, move-out, and downsizing projects', 'Mixed household items carried out by the crew']],
    'construction-debris': ['Construction Debris Removal', 'Construction debris removal in Metro Atlanta for renovation waste and project-site cleanup.', 'IMG_4337.jpg', ['Renovation debris and removed fixtures', 'Wood, drywall, packaging, and jobsite clutter', 'Scheduling that works around your project']],
    'commercial-junk-removal': ['Commercial Junk Removal', 'Commercial junk removal in Metro Atlanta for offices, retail spaces, warehouses, and property cleanouts.', 'IMG_2968.jpg', ['Office furniture, equipment, and fixtures', 'Retail, warehouse, and property cleanouts', 'Planned pickups for businesses and property teams']]
  };
  const page = pages[document.body.dataset.service];
  if (!page) return;

  document.title = `${page[0]} in Atlanta & Suwanee, GA | Big Boys`;
  document.getElementById('serviceTitle').textContent = `${page[0]} in Atlanta & Suwanee`;
  document.getElementById('serviceIntro').textContent = page[1];
  document.getElementById('serviceContent').innerHTML = `<div class="service-proof"><div><span class="eyebrow">Big Boys service</span><h2>A straightforward way to clear the space</h2><p>Choose item-based or load-size pricing, tell us about access and timing, and request a pickup. The crew carries, loads, and removes the items included in your quote.</p><h2>What we can take</h2><ul>${page[3].map(item => `<li>${item}</li>`).join('')}</ul></div><figure><img src="../photos/junk-removal/${page[2]}" alt="${page[0]} job prepared for Big Boys pickup" loading="lazy" decoding="async"><figcaption>Real junk-removal work from the Big Boys photo library.</figcaption></figure></div><section class="service-details"><div><span class="eyebrow muted">What to expect</span><h2>Price first. Pickup second.</h2><ol><li><strong>Choose your price path.</strong> Select individual items for detail or a load size for a bulk estimate.</li><li><strong>Share the job details.</strong> Let us know about stairs, disassembly, access, or a preferred pickup time.</li><li><strong>Request your pickup.</strong> Review the estimate, then send a booking request for confirmation.</li></ol></div><aside><h2>Need help planning?</h2><p>For an unusually large, heavy, or time-sensitive job, call us and we--™ll help you decide on the best pickup approach.</p><a class="btn btn-outline" href="tel:+14706606874">Call (470) 660-6874</a></aside></section><section class="service-faq" aria-labelledby="serviceFaqTitle"><span class="eyebrow muted">Service FAQ</span><h2 id="serviceFaqTitle">Questions about ${page[0].toLowerCase()}</h2><details open><summary>Do I need to move everything to the curb?</summary><p>No. Let us know where the items are located when you request your pickup. The crew can remove items from inside, outside, garages, basements, and other accessible areas.</p></details><details><summary>How is the price determined?</summary><p>You can start with item pricing or a load-size estimate. The quote flow also captures details that can affect the work, such as stairs or disassembly.</p></details><details><summary>Do you offer same-day service?</summary><p>Same-day availability depends on the current schedule. Start your quote or call us to check the earliest available pickup window.</p></details></section><h2>Serving Atlanta, Suwanee, and Metro Atlanta</h2><p>Visit the <a href="../atlanta/">Atlanta service page</a> or <a href="../suwanee/">Suwanee service page</a>, or browse all <a href="../service-areas/index.html">Metro Atlanta service areas</a>.</p><div class="cta-row"><a class="btn btn-primary" href="../get-a-price-quote.html">Get a Price Quote</a><a class="btn btn-outline" href="index.html">Explore All Services</a></div>`;

  const shell = document.createElement('script');
  shell.src = '../site-shell.js';
  shell.dataset.root = '../';
  document.body.append(shell);
})();
