(function () {
  const services = {
    'furniture-removal': {title:'Furniture Removal', image:'IMG_6412.jpg', intro:'Couches, tables, dressers, recliners, bed frames, and other bulky furniture removed from homes, apartments, offices, garages, and storage spaces across Atlanta and Suwanee', items:['Couches, sectionals, loveseats, and recliners','Dining tables, chairs, desks, and bookcases','Dressers, wardrobes, bed frames, and bedroom sets','Office furniture and small commercial fixtures'], situations:['Replacing worn or damaged furniture','Preparing for a move, sale, or tenant turnover','Downsizing or clearing an inherited property','Making room after a delivery or renovation'], prep:'Remove personal belongings from drawers and shelves, identify pieces that need disassembly, and share stairs, elevator, hallway, parking, or gate details with the request'},
    'appliance-removal': {title:'Appliance Removal', image:'IMG_2820.jpg', intro:'Old refrigerators, freezers, washers, dryers, stoves, dishwashers, and other household appliances hauled away without requiring you to move them to the curb', items:['Refrigerators, freezers, and ice makers','Washers, dryers, stoves, and dishwashers','Microwaves and small appliances with a larger pickup','Detached appliance accessories and packaging'], situations:['Replacing an outdated or broken appliance','Clearing a rental or preparing a property for sale','Removing garage or basement appliances','Combining appliance removal with furniture or household junk'], prep:'Disconnect water, gas, and electrical connections before arrival. Empty food, liquids, detergent, and personal items, then tell the team where the appliance is located'},
    'mattress-removal': {title:'Mattress Removal and Disposal', image:'IMG_6386.jpg', intro:'Mattresses, box springs, bed frames, headboards, and bedroom furniture removed from any accessible room, garage, storage space, or curbside location', items:['Twin, full, queen, and king mattresses','Box springs and adjustable bed bases','Bed frames, headboards, and bedroom sets','Bagged bedding with a larger removal job'], situations:['Upgrading a bedroom or replacing a damaged mattress','Moving, downsizing, or clearing a rental','Estate cleanouts and guest-room updates','Removing bed frames and bedroom furniture together'], prep:'Strip bedding, remove personal items, and tell the crew whether the mattress is upstairs, in a basement, or behind narrow access. Mention stains, water damage, or pest concerns before booking'},
    'hot-tub-removal': {title:'Hot Tub Removal', image:'IMG_6127.jpg', intro:'Residential hot tubs, spas, covers, steps, and surrounding outdoor clutter removed with a clear plan for size, access, disconnection, and heavy lifting', items:['Freestanding residential hot tubs and spas','Hot tub covers, stairs, and accessories','Detached pumps, filters, and related equipment','Outdoor furniture or debris included in the scope'], situations:['Removing a nonworking or unused spa','Preparing a patio, deck, or yard for renovation','Clearing a property before listing or turnover','Reclaiming outdoor space for another use'], prep:'Disconnect electricity, gas, and water through the appropriate qualified provider. Drain the tub completely and share gate width, deck height, fencing, and access photos before scheduling'},
    'yard-waste-removal': {title:'Yard Waste Removal', image:'IMG_5080.jpg', intro:'Branches, brush, bagged yard material, storm debris, outdoor furniture, and general backyard clutter removed from residential and commercial properties', items:['Bagged leaves and routine yard debris','Branches, brush, and storm cleanup piles','Old planters, outdoor furniture, and garden clutter','Mixed non-hazardous debris from outdoor projects'], situations:['Seasonal yard cleanup and storm preparation','Post-landscaping or tree-trimming cleanup','Preparing a property for sale or inspection','Clearing patios, sheds, and outdoor storage areas'], prep:'Keep yard material separate from household trash when possible, avoid mixing soil or hazardous chemicals, and describe the pile size, access path, and distance to the parking area'},
    cleanouts: {title:'Garage, Basement, and Estate Cleanouts', image:'IMG_5771.jpg', intro:'Complete cleanout support for garages, basements, attics, storage rooms, estates, move-outs, downsizing projects, and properties with mixed household contents', items:['Garage, basement, attic, and storage-room contents','Estate, move-out, and downsizing removal piles','Furniture, boxes, appliances, and household clutter','Rental turnover and inherited-property contents'], situations:['Preparing for a move or home sale','Managing an estate or inherited property','Reclaiming storage space after years of accumulation','Clearing a rental, foreclosure, or renovation area'], prep:'Separate keepsakes, documents, donations, and items for removal before pickup day. Work room by room, label anything that must stay, and share parking, stairs, and access requirements'},
    'construction-debris': {title:'Construction Debris Removal', image:'IMG_4337.jpg', intro:'Renovation waste, removed fixtures, wood, drywall, packaging, and non-hazardous project debris cleared from homes, businesses, and active work areas', items:['Wood, drywall, trim, and renovation scraps','Removed cabinets, fixtures, and flooring','Cardboard, packaging, and jobsite clutter','Non-hazardous debris from repairs and remodeling'], situations:['Kitchen, bathroom, and room renovations','Rental turnover repairs and property refreshes','Contractor cleanup between project phases','Homeowner remodeling and DIY projects'], prep:'Keep hazardous materials, paint, chemicals, and regulated waste separate. Stack or contain loose debris when practical and estimate weight, material type, and carrying distance'},
    'commercial-junk-removal': {title:'Commercial Junk Removal', image:'IMG_2968.jpg', intro:'Office furniture, retail fixtures, equipment, packaging, warehouse clutter, and unwanted property contents removed with scheduling built around business operations', items:['Desks, chairs, cubicles, and office furniture','Retail fixtures, shelving, displays, and packaging','Warehouse contents and non-hazardous equipment','Property cleanouts and tenant-turnover material'], situations:['Office moves, renovations, and furniture replacement','Retail closures or display changes','Warehouse organization and inventory cleanup','Property-management turnovers and abandoned contents'], prep:'Identify building hours, loading areas, freight elevators, security requirements, parking restrictions, and any items that need special handling before the pickup is confirmed'}
  };

  const page = services[document.body.dataset.service];
  if (!page) return;
  document.title = `${page.title} in Atlanta and Suwanee GA | Big Boys`;
  document.getElementById('serviceTitle').textContent = `${page.title} in Atlanta and Suwanee`;
  document.getElementById('serviceIntro').textContent = page.intro;
  const keywords = document.createElement('meta');
  keywords.name = 'keywords';
  keywords.content = `${page.title.toLowerCase()} Atlanta, ${page.title.toLowerCase()} Suwanee, Metro Atlanta junk removal, same-day junk pickup, Big Boys Junk Removal`;
  document.head.append(keywords);

  document.getElementById('serviceContent').innerHTML = `
    <div class="service-proof"><div><span class="eyebrow">Big Boys service</span><h2>Professional ${page.title.toLowerCase()} without the heavy lifting</h2><p>${page.intro}. The crew can remove items from inside or outside when access is safe and included in the confirmed scope</p><h2>Common items we remove</h2><ul>${page.items.map(item => `<li>${item}</li>`).join('')}</ul></div><figure><img src="../photos/junk-removal/${page.image}" alt="${page.title} project completed by Big Boys in Metro Atlanta" loading="lazy" decoding="async"><figcaption>Real Big Boys junk removal work in Metro Atlanta</figcaption></figure></div>
    <section class="service-details"><div><span class="eyebrow muted">A useful starting estimate</span><h2>Choose the pricing path that matches the job</h2><p>Use item pricing when you have a short, specific list. Use load-size pricing when the job includes mixed material or several rooms. Add stairs, disassembly, access notes, and a preferred pickup window before reviewing the estimate</p><ol><li><strong>Describe the scope</strong> Choose individual items or the closest trailer fraction</li><li><strong>Add labor and access details</strong> Include stairs, tight paths, parking, gates, elevators, and disassembly</li><li><strong>Request a pickup</strong> Share contact details, address, date, time preference, and final notes</li><li><strong>Confirm before work begins</strong> The team reviews route availability, material, access, and final scope</li></ol></div><aside><h2>Need help choosing?</h2><p>Call when the project has unusually heavy items, several rooms, difficult access, or a firm deadline</p><a class="btn btn-outline" href="tel:+14706606874">Call (470) 660-6874</a></aside></section>
    <section class="service-use-cases"><div><span class="eyebrow muted">When customers call</span><h2>Common reasons to schedule ${page.title.toLowerCase()}</h2><div class="use-case-grid">${page.situations.map((item, index) => `<article><span>0${index + 1}</span><p>${item}</p></article>`).join('')}</div></div></section>
    <section class="local-guide"><div><span class="eyebrow muted">Prepare for pickup day</span><h2>A few details make the removal easier</h2><p>${page.prep}</p><ol><li><strong>Make the scope clear</strong> Point out everything that should go and label anything that must stay</li><li><strong>Create safe access</strong> Clear walking paths and mention stairs, gates, elevators, pets, or building rules</li><li><strong>Confirm timing</strong> Keep the phone available around the requested window in case the crew needs an access update</li></ol></div><aside><h3>Combine services in one request</h3><p>You can include furniture, appliances, boxes, outdoor items, and other non-hazardous material together. Load-size pricing may be simplest for mixed jobs</p><a href="../get-a-price-quote.html">Build an Estimate</a></aside></section>
    <section class="service-faq" aria-labelledby="serviceFaqTitle"><span class="eyebrow muted">Service FAQ</span><h2 id="serviceFaqTitle">Questions about ${page.title.toLowerCase()}</h2><details open><summary>Do I need to move everything to the curb?</summary><p>No. Tell the team where the items are located. The crew can carry approved items from accessible rooms, garages, basements, offices, yards, or curbside locations</p></details><details><summary>How is the starting price calculated?</summary><p>Choose item pricing for a known list or load-size pricing for mixed material. Access, stairs, disassembly, weight, route, and disposal requirements can affect the confirmed scope</p></details><details><summary>Can I request same-day service?</summary><p>Same-day availability depends on route capacity, project size, and when the request is received. Call early when timing is important</p></details><details><summary>What happens to removed items?</summary><p>Reusable and recyclable material may be diverted when practical and when an appropriate destination is available. Disposal depends on condition, material, and local options</p></details><details><summary>What items require another provider?</summary><p>Hazardous chemicals, fuels, medical waste, and certain regulated material may need a specialized disposal provider. Call before booking if you are unsure</p></details></section>
    <section class="service-local"><h2>${page.title} across Metro Atlanta</h2><p>Big Boys serves customers from Atlanta and Suwanee throughout surrounding communities including Marietta, Decatur, Roswell, Alpharetta, Buford, Lawrenceville, Sandy Springs, Tucker, Chamblee, Brookhaven, and more. Visit the <a href="../service-areas/index.html">service area directory</a> or call to confirm your ZIP code</p><div class="cta-row"><a class="btn btn-primary" href="../get-a-price-quote.html">Get My Price</a><a class="btn btn-outline" href="index.html">Explore All Services</a></div></section>`;

  const shell = document.createElement('script');
  shell.src = '../site-shell.js';
  shell.dataset.root = '../';
  document.body.append(shell);
})();
